//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVTComment.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NiconicoUserId {
            get {
                return ((string)(this["NiconicoUserId"]));
            }
            set {
                this["NiconicoUserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NiconicoPassword {
            get {
                return ((string)(this["NiconicoPassword"]));
            }
            set {
                this["NiconicoPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:15")]
        public global::System.TimeSpan NichanThreadSearchInterval {
            get {
                return ((global::System.TimeSpan)(this["NichanThreadSearchInterval"]));
            }
            set {
                this["NichanThreadSearchInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:01")]
        public global::System.TimeSpan NichanResCollectInterval {
            get {
                return ((global::System.TimeSpan)(this["NichanResCollectInterval"]));
            }
            set {
                this["NichanResCollectInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte ChatOpacity {
            get {
                return ((byte)(this["ChatOpacity"]));
            }
            set {
                this["ChatOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TVTComment.Model.Serialization.ChatModRuleEntity[] ChatModRules {
            get {
                return ((TVTComment.Model.Serialization.ChatModRuleEntity[])(this["ChatModRules"]));
            }
            set {
                this["ChatModRules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle NgSettingWindowPosition {
            get {
                return ((global::System.Drawing.Rectangle)(this["NgSettingWindowPosition"]));
            }
            set {
                this["NgSettingWindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDefaultChatCollectService {
            get {
                return ((bool)(this["UseDefaultChatCollectService"]));
            }
            set {
                this["UseDefaultChatCollectService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LiveDefaultChatCollectServices {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LiveDefaultChatCollectServices"]));
            }
            set {
                this["LiveDefaultChatCollectServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecordDefaultChatCollectServices {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecordDefaultChatCollectServices"]));
            }
            set {
                this["RecordDefaultChatCollectServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double WindowOpacity {
            get {
                return ((double)(this["WindowOpacity"]));
            }
            set {
                this["WindowOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowTopmost {
            get {
                return ((bool)(this["WindowTopmost"]));
            }
            set {
                this["WindowTopmost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TVTComment.ViewModels.ListViewColumnViewModel[] ChatListViewColumnSettings {
            get {
                return ((TVTComment.ViewModels.ListViewColumnViewModel[])(this["ChatListViewColumnSettings"]));
            }
            set {
                this["ChatListViewColumnSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color NichanChatColor {
            get {
                return ((global::System.Drawing.Color)(this["NichanChatColor"]));
            }
            set {
                this["NichanChatColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<RectangleF xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <Location>
    <X>NaN</X>
    <Y>NaN</Y>
  </Location>
  <Size>
    <Width>330</Width>
    <Height>500</Height>
  </Size>
  <X>NaN</X>
  <Y>NaN</Y>
  <Width>330</Width>
  <Height>500</Height>
</RectangleF>")]
        public global::System.Drawing.RectangleF MainWindowPosition {
            get {
                return ((global::System.Drawing.RectangleF)(this["MainWindowPosition"]));
            }
            set {
                this["MainWindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ChatPreserveCount {
            get {
                return ((int)(this["ChatPreserveCount"]));
            }
            set {
                this["ChatPreserveCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TVTComment.Model.Serialization.ChatCollectServiceCreationPresetEntity[] ChatCollectServiceCreationPresets {
            get {
                return ((TVTComment.Model.Serialization.ChatCollectServiceCreationPresetEntity[])(this["ChatCollectServiceCreationPresets"]));
            }
            set {
                this["ChatCollectServiceCreationPresets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearChatsOnChannelChange {
            get {
                return ((bool)(this["ClearChatsOnChannelChange"]));
            }
            set {
                this["ClearChatsOnChannelChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ChatPostMailTextExamples {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ChatPostMailTextExamples"]));
            }
            set {
                this["ChatPostMailTextExamples"] = value;
            }
        }
    }
}
